### ISSUE TITLE
Why can not reproduce the experiment in 32GB memory?

### ISSUE THREAD

**Issue by hoL1day** [yfhanhust/MiniBatchSpectralClustering#1]
In paper, you said "All our experiments are conducted under Ubuntu Linux 14.04 with 10-core CPU and 20GB memory." But now I run the code with 32GB memory, the same code and the sam dataset(581012 samples), it came out as below. I know that it is sklearn's memory error, but how can you run such a big dataset in 20GB memory?

Traceback (most recent call last):
  File "sgd_spectral.py", line 280, in <module>
    affinity_matrix = rbf_kernel(train_data,gamma = gamma_value)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 842, in rbf_kernel
    K = euclidean_distances(X, Y, squared=True)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 246, in euclidean_distances
    distances = safe_sparse_dot(X, Y.T, dense_output=True)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/sklearn/utils/extmath.py", line 140, in safe_sparse_dot
    return np.dot(a, b)
MemoryError

**Comment by yfhanhust** [comment]
Hi, thanks for your interests in our work. For experimental study in the paper, we modified the original rbf_kernel function with CPython. We don't output the whole pairwise kernel matrix, instead, we only store the upper triangular part, since the kernel matrix is symmetric. In case the memory is still out of use, we conduct memory map in Python to save the memory cost while slightly sacrifice computational speed. This code is used for demonstrating the flow of the proposed algorithm without touching implementation details. For databases of large sizes, like shuttle, mnist and covtype, we observed the same issue as you pointed out when we directly ran this demo code on RAM-limited platforms. It is recommended to run this demo code with larger memory, e.g. 120GiB RAM, to reproduce the NMI scores.
